name: Mycropython Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      REPO_NAME: ${{ vars.GITHUB_REPOSITORY }}
      IMG_VER: "****"

    steps:
    - name: Pre check
      run: |
        echo "Precheck"
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        echo "Repository: ${{ env.REPO_NAME }}"
        set-env IMG_VER=$(date +%Y%m%d%H%M)
        echo "Image version: ${{ env.IMG_VER }}"
        echo "Docker username: ${{ env.DOCKER_USERNAME }}"
        echo "All environments: "
        env
        echo "Docker password (test): "
        echo ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        set-env VERTAG=${{ env.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.IMG_VER }}
        set-env LATESTTAG=${{ env.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.IMG_VER }}
        docker build . --file Dockerfile --tag $VERTAG
        docker image tag $VERTAG $LATESTTAG
        docker push $VERTAG
        docker push $LATESTTAG
