name: Mycropython Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

    steps:
      - name: prune
        run: |
          echo ===== Prune docker images =====
          docker image prune --force

      - name: Pre check
        run: |
          echo "Precheck"
          export REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          echo "Repository: $REPO_NAME"
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"

          export IMG_VER=$(date +%Y%m%d%H%M)
          echo "Image version: $IMG_VER"
          echo "IMG_VER=$IMG_VER" >> "$GITHUB_ENV"

          echo "Docker username: ${{ env.DOCKER_USERNAME }}"

          echo "Docker password (test): ${{ secrets.DOCKER_PASSWORD }}"
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/$REPO_NAME:$IMG_VER
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |              
            INCLUDE_MONGODBTOOLS=true
            PREINSTALL_LIBS=true
